### ISSUE TITLE
Adding function code

### ISSUE THREAD

**Issue by real050280** [froatsnook/bardcode#4]
Hello,

How do you guys add Function code (ie FNC1) ?

My scanner always fails because of a missing function code FNC1 after the STARTC.
I am using CODE128 by the way.

Sample options:
```
const barSvg = bardcode.drawBarcode('svg', '(00)12345678901234567890',
    {
        width: 250,
        height: 95,
        horizontalAlign: 'center',
        verticalAlign: 'middle',
        moduleWidth: 7
    });
const barcodePath = srtps.rectsToPath(barSvg);
```

Actual results from the scanner:
STARTC0012345678901234567890

Expected results:
STARTCFNC10012345678901234567890

How to resolve this ?

Thank you very much.

**Comment by froatsnook** [comment]
Hey there,

I've never had to do this, but glancing at the code it looks like it should be possible.  Currently when you call `drawBarcode`, it first calls `encodeCode128`, and then `drawBitsBarcode`.  While `drawBarcode` checks whether its input is a string, `encodeCode128` doesn't.  You can pass an array of characters to it, instead of a string, which lets you encode special characters like `"FNC 1"`.

```javascript
const text = "00123456789";
const chars = text.split("");
chars.unshift("FNC 1");
const encodeData = bardcode.encodeCode128(chars);
const barSvg = bardcode.drawBitsBarcode("svg", options, encodeData);
```

Let me know if this doesn't work and I can try to find another solution.  And if this works, getting rid of the string check in `drawBarcode` will make this cleaner in a future release.

**Comment by real050280** [comment]
Hello froatsnook,

I think encodeCode128 above works correctly, however, when converted the output from SVG to PATH, it always gives me an error.

Please note that I need to convert the output of bardcode to PATH for me to control its display (requirements).

**Comment by froatsnook** [comment]
What error does it give you?  What do you mean by converting SVG to PATH?  Is that a vector file format?

**Comment by real050280** [comment]
Hello,

It says "Unsupported number: NaN".
bardcode.drawBarcode function doesn't give me such error.

I need to convert it to PATH inorder for me to write it into a pdf page using PDFKIT.
However, the said error prevented me from progressing.

Thank you and best regards.

**Comment by froatsnook** [comment]
Ah, this is making more sense.  I didn't see your call to `srtps.rectsToPath` before.

Can you paste the result of `drawBitsBarcode`?  Maybe it's not a valid SVG.  And can you paste the code where you're calling `drawBitsBarcode`?  Possibly is some invalid input (e.g. `"FNC1"` instead of `"FNC 1"`).

EDIT: an invalid character probably wouldn't explain it since it should throw an error.

**Comment by real050280** [comment]
Hello froatsnook,

Sorry for the long delay. Below is the output of `drawBitsBarcode `and the source code for it.

```
<svg xmlns='http://www.w3.org/2000/svg' width='210.000' height='90' fill='black'>
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
<rect width='NaN' height='90' x='NaN' y='0' />
</svg>
```
test.js

```
'use strict';

const bardcode = require('bardcode');
const srtps = require('srtps');

const text = "00123456789";
const chars = text.split("");
chars.unshift("FNC 1");

const encodeData = bardcode.encodeCode128(chars);

const barSvg = bardcode.drawBitsBarcode("svg", {
  width: 210,
  height: 90,
  horizontalAlign: 'center',
  verticalAlign: 'middle'
}, encodeData);

console.log(barSvg);

const barcodePath = srtps.rectsToPath(barSvg);

```

**Comment by froatsnook** [comment]
OK, I see the problem.  When you call `drawBitsBarcode` directly, then it doesn't take over the  [default options](https://github.com/froatsnook/bardcode/blob/master/lib/drawBarcode.js#L3).  Here's how to fix it:

```javascript
'use strict';

const bardcode = require('bardcode');
const srtps = require('srtps');

const text = "00123456789";
const chars = text.split("");
chars.unshift("FNC 1");

const encodeData = bardcode.encodeCode128(chars);

const barSvg = bardcode.drawBitsBarcode("svg", {
    type: "Code 128",
    hasChecksum: false,
    x: 0,
    y: 0,
    moduleWidth: 2.892,
    height: 90,
    horizontalAlign: "center",
    verticalAlign: "middle",
    quietZoneSize: 10,
    angle: 0,
    maxWidth: Infinity,
    width: 210
}, encodeData);

console.log(barSvg);

const barcodePath = srtps.rectsToPath(barSvg);
```

I'm working on improving this, but the above should get you sorted for now!

**Comment by real050280** [comment]
Thanks froatsnook. It is fixed indeed.

**Comment by froatsnook** [comment]
@real050280 I just pushed 2.0.0 which lets you output to path directly.  Also you don't have to call `drawBitsBarcode` directly.

```javascript
const text = "00123456789";
const chars = text.split("");
chars.unshift("FNC 1");
const barPath = bardcode.drawBarcode('path', chars,
    {
        width: 250,
        height: 95,
        horizontalAlign: 'center',
        verticalAlign: 'middle',
        moduleWidth: 7
    });
```

Let me know if you try it out.  It's not on npm (someone else published there actually), but I think you can do:

```
npm install froatsnook/bardcode
```

**Comment by real050280** [comment]
Hello froatsnook,

I have tried it and it works awesome!
However, I have additional question for you.
If I need to insert multiple function codes in the text (ie START and MIDDLE), how should I do that.
Also, I tried using the 'angle' option and it seems like it doesn't do anything on the output itself.

Btw, here is how I used it in our project.
*note: some contents were omitted.

test.js
```
'use strict';

const fs = require('fs');
const bardcode = require('bardcode');
const PDFDocument = require('pdfkit');

const text = "00123456789";
const chars = text.split("");
chars.unshift("FNC 1");

const barcodePath = bardcode.drawBarcode("path", chars, {
  width: 210,
  height: 90,
  moduleWidth: 7,
  horizontalAlign: "center",
  verticalAlign: "middle",
});

try {
  let doc = new PDFDocument({
    size: 'A4',
    margin: 0,
  });

  const filename = 'test';
  let pdfFilename = `./test/${filename}.pdf`;

  doc.pipe(fs.createWriteStream(pdfFilename));

  doc
  .translate(30, 30).path(barcodePath).fill('#000').stroke()
  .text(text,32,95)
  .end();
} catch(err) {
  console.log({message: 'ERROR occurred.', description: err});
}
```

**Comment by froatsnook** [comment]
You can put in other function codes by inserting them in the array of characters, of course, but I'm not sure what START and MIDDLE function codes are.  You can find the full list [here](https://github.com/froatsnook/bardcode/blob/4f38a3ba8627d5dd51410234575e55c886a4085b/lib/Code128.js#L14) which I took [from wikipedia](https://en.wikipedia.org/wiki/Code_128#Bar_code_widths).

Unfortunately `angle` isn't currently one of the [available options](https://github.com/froatsnook/bardcode#path) for path/svg.  It can be implemented using a 2d rotation matrix.  PR welcome! ;)

**Comment by real050280** [comment]
Sorry for the confusion about the START and MIDDLE above :)
What I mean is that, inserting a FNC1 character in the START and MIDDLE of the text.

So the expected output when scanned is like:
STARTCFNC100123456789FNC1123456789

In the future, some combinations maybe done depending on the requirements.

But, looking further, I noticed that such format is better solved by SSCC or GS1-128 code types of which your library is not capable at the moment.

**Comment by froatsnook** [comment]
You can use [`Array.prototype.splice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) to insert a `"FNC 1"` string in the middle of your array.  Or just pass an array directly like `["FNC 1", "0", "1", "2", "FNC 1", "3", "4", "5"]`.

It looks like SSCC and GS1-128 are just application standards built on top of CODE 128, so you can already build such barcodes using this library.
