### ISSUE TITLE
Print Barcode Sticker

### ISSUE THREAD

**Issue by ihussain1024** [froatsnook/bardcode#5]
Is there any way to print the barcode directly from browser ?

**Comment by froatsnook** [comment]
Hey @ihussain1024.  What printer are you using?

**Comment by ihussain1024** [comment]
Zebra TLP 2844

**Comment by froatsnook** [comment]
Have you tried `window.print()`?

**Comment by ihussain1024** [comment]
@froatsnook 
This printer supports raw printing only. Doesn't support `window.print()`

**Comment by froatsnook** [comment]
Which browser are you using?  I think you'd have to use a browser extension like [this](https://github.com/receipt-print-hq/chrome-raw-print) or maybe use electron with [this](https://github.com/tojocky/node-printer).
