### ISSUE TITLE
UPC-A: "Invalid checksum"

### ISSUE THREAD

**Issue by wolfgang42** [froatsnook/bardcode#7]
I don't know what the difference is exactly, but when I upgrade to 949a463d5dfe107905f4b0de6c440c04b49be504 or beyond, I start getting `Error: Invalid checksum.` when I try to generate UPC-A barcodes. I don't immediately see an glaring problem, but that commit is very large so it wouldn't necessarily be obvious.

Example that this is broken with:
```javascript
bardcode.drawBarcode('svg', '846823000342', {
	type: 'UPC-A',
	hasChecksum: true,
	horizontalAlign: "center",
	height: 90/3,
	maxWidth: 90 * 1.7,
})
```

**Comment by froatsnook** [comment]
Thanks Wolfgang :). Fixed now.
