### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by wolfgang42** [froatsnook/bardcode#8]
I see that you've created a release for 2.0.1, but the NPM package is still on 1.0.0.

**Comment by froatsnook** [comment]
I don't control the npm package!  But I wrote support@npmjs.com:

> Hi there,
> 
> Someone published my package a few years ago, which was fine.  But now they're not updating it and it would be convenient if I could publish changes on npm since a user requested the new version.  Is there any way to do this?
> 
> https://github.com/froatsnook/bardcode
> Proof here: https://github.com/froatsnook/bardcode/issues/7
> 
> Thanks!

**Comment by enyachoke** [comment]
@froatsnook  Sorry about this I have now transferred the package ownership to you. Keep up the good work.

**Comment by froatsnook** [comment]
Thanks @enyachoke!

2.0.1 is published on npm :).
